# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afdba060d09f2f799ec94ca3aa075ce749fde9f7c86bed9d19156f0a52a436be22dbfa032f704ce6988c6777e082858c381869fa0dd0278cb4846e2828c1366

test:
  secret_key_base: d44610056a17deaa9f37166ee65dcc9d177f13153e20fac6d1b4c3e244db9131d0cfc397a036dba953c2591503db117fdb79ae1a9cdd95cb8ddee59560b0a646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
